<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <EmbeddedResource Include="..\..\assets\mic-muted.png" Link="Assets\mic-muted.png" />
    <EmbeddedResource Include="..\..\assets\mic-unmuted.png" Link="Assets\mic-unmuted.png" />
    <EmbeddedResource Include="..\..\assets\device-disconnected.png" Link="Assets\device-disconnected.png" />
    <EmbeddedResource Include="..\..\assets\server-disconnected.png" Link="Assets\server-disconnected.png" />
    <EmbeddedResource Include="..\..\assets\pause.png" Link="Assets\pause.png" />
    <EmbeddedResource Include="..\..\assets\app.ico" Link="Assets\app.ico" />
  </ItemGroup>

</Project>
