<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <LangVersion>latest</LangVersion>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MSTest" Version="4.0.2" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Microsoft.VisualStudio.TestTools.UnitTesting" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\MicHelper.Shared\MicHelper.Shared.csproj" />
    <ProjectReference Include="..\..\src\MicHelper.Server\MicHelper.Server.csproj" />
    <ProjectReference Include="..\..\src\MicHelper.Client\MicHelper.Client.csproj" />
  </ItemGroup>

</Project>
